---
title: "Automatic import files to Cytoscape and color network"
format: html
date: "2025-12-14"
bibliography: ../../../refs-stat-anal.bib
execute:
  fig-format: png
  fig.dpi: 300
---

*DNA transcription-factor activity* Go category and descendants (childs).
The aim of the script is to reproduce manual import of files and coloring of network in Cytoscape using RCy3 package.
Automatic generation of networks for all clusters.

Built with R version `r getRversion()`

## R Preliminaries

Environment cleaning and set-up

```{r setup}
#| include: false
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(root.dir = "/home/mj/project1-stat/vs-day-one/leaf/scripts")
```

```{r packages}
#| eval: false
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("RCy3")
```

```{r}
#| output: false

# load package
library(RCy3)

# check connection to Cytoscape
cytoscapePing()

# Clean working directory
rm(list=ls())
```

```{r format all}
clusters <- vector("list", length = 12)

# Przy 13. pisze o zbyt małej sieci i nie liczy parametrów sieci - zostawiam mimo to

for (i in c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13)) {
  input_file=paste0("../results/network/cluster_", i, "_400_tran-reg.txt")
  
  cl = read.table(input_file, header=TRUE, stringsAsFactors = FALSE, sep='\t', quote = "")
  
  # NODE info, rbind columns from source node and target node
src=unique(cl[c('uniprot1', 'ensembl1', 'desc1', 'cluster1', 'member1')])
trg=unique(cl[c('uniprot2', 'ensembl2', 'desc2', 'cluster2', 'member2')])
# names must be the same
names(src) <- c('id', 'ensembl', 'desc', 'cluster', 'member')
names(trg) <- c('id', 'ensembl', 'desc', 'cluster', 'member')
# rbind
node.info <- unique(rbind(src, trg))

# sort node info table - in case of UPs multimapping to NAMs select NAM with cluster (sorts numerically, NAs are before numbers. During network generation the last row for each id is selected)
## POTENTIAL PROBLEM, if UP have NAMs from >1 cluster it selects the one with the highest cluster number!!!
## REQUIRE MANUAL CHECKING
ord <- order(node.info[[1]],                 # kolumna 1 – sortowanie leksykograficzne
             as.numeric(node.info[[4]]),    # kolumna 4 – sortowanie numeryczne
             na.last = FALSE)

node.info_srt <- node.info[ord, ]

# EDGE table
edge.info=unique(cl[,!names(cl) %in% c('ensembl1', 'desc1', 'cluster1', 'member1', 'ensembl2', 'desc2', 'cluster2', 'member2')])

createNetworkFromDataFrames(
  title=gsub("../results/network/", "", input_file),
  collection="leaf networks",
  nodes=node.info_srt,
  source.id.list="uniprot1",
  target.id.list="uniprot2",
  edges=edge.info
)

# PROBLEM - ZA KAŻDĄ ZMIANĄ LICZBY KLASTRÓW TRZEBA KOLOROWAĆ RĘCZNIE W CYTOSCAPE, ROBIĆ SCREEN I POBIERAĆ KOOR W GIMP.

# color nodes from main cluster
setNodeColorMapping(
  "cluster",
  c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13"),
  c("#ffeea0", "#fedd8e", "#fecd80", "#febc6e", "#fead5c", "#fe9d4e", "#fd8c3c", "#f27638", "#e85f35", "#dd4631", "#d32f2d", "#c9182a", "#bd0026"),
  mapping.type="c"
)

setNodeColorBypass(
  t(subset(node.info_srt, cluster == i, select=c("id"))),
  "#78c679"
)

# run "Analyze network" to get degree values
analyzeNetwork()

setNodeSizeMapping(
  "Degree",
  c(1, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100),
  c(20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70),
  mapping.type="c"
)
}
```


## References